const linkdInBuds = [
    {
        id:'1',
        avatarUrl: 'https://images.pexels.com/photos/771742/pexels-photo-771742.jpeg?h=350&auto=compress&cs=tinysrgb',
        username: 'Jill Upthehill',
        job: 'Piano Tutor',
        connections: 400,
        connectButton: "Connect",
    },
    {
        id:'2',
        avatarUrl: 'https://images.pexels.com/photos/771742/pexels-photo-771742.jpeg?h=350&auto=compress&cs=tinysrgb',
        username: 'Jack Hack',
        job: 'React Developer',
        connections: 666,
        connectButton: "Invite",
    },
    {
        id:'3',
        avatarUrl: 'https://images.pexels.com/photos/771742/pexels-photo-771742.jpeg?h=350&auto=compress&cs=tinysrgb',
        username: 'Jazzy Jeff',
        job: 'Artist',
        connections: 3,
        connectButton: "Connect",
    },
    {
        id:'4',
        avatarUrl: 'https://images.pexels.com/photos/771742/pexels-photo-771742.jpeg?h=350&auto=compress&cs=tinysrgb',
        username: 'Jill Upthehill',
        job: 'Piano Tutor',
        connections: 400,
        connectButton: "Connect",
    },
    {
        id:'5',
        avatarUrl: 'https://images.pexels.com/photos/771742/pexels-photo-771742.jpeg?h=350&auto=compress&cs=tinysrgb',
        username: 'Jack Hack',
        job: 'React Developer',
        connections: 666,
        connectButton: "Invite",
    },
    {
        id:'6',
        avatarUrl: 'https://images.pexels.com/photos/771742/pexels-photo-771742.jpeg?h=350&auto=compress&cs=tinysrgb',
        username: 'Jazzy Jeff',
        job: 'Artist',
        connections: 3,
        connectButton: "Connect",
    },
    {
        id:'7',
        avatarUrl: 'https://images.pexels.com/photos/771742/pexels-photo-771742.jpeg?h=350&auto=compress&cs=tinysrgb',
        username: 'Jill Upthehill',
        job: 'Piano Tutor',
        connections: 400,
        connectButton: "Connect",
    },
    {
        id:'8',
        avatarUrl: 'https://images.pexels.com/photos/771742/pexels-photo-771742.jpeg?h=350&auto=compress&cs=tinysrgb',
        username: 'Jack Hack',
        job: 'React Developer',
        connections: 666,
        connectButton: "Invite",
    },
    {
        id:'9',
        avatarUrl: 'https://images.pexels.com/photos/771742/pexels-photo-771742.jpeg?h=350&auto=compress&cs=tinysrgb',
        username: 'Jazzy Jeff',
        job: 'Artist',
        connections: 3,
        connectButton: "Connect",
    },
];

export default linkdInBuds;